// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOjW1IrUtqTpMWHm_GG4gSib8TGBTmHi4',
    appId: '1:804705700879:web:13a8f24cf4a19794b9e77a',
    messagingSenderId: '804705700879',
    projectId: 'vinner-308ca',
    authDomain: 'vinner-308ca.firebaseapp.com',
    databaseURL: 'https://vinner-308ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vinner-308ca.appspot.com',
    measurementId: 'G-VECRZRKWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvBpd0fbnh3aUQTU3B74n_M5IV8zGbrv8',
    appId: '1:804705700879:android:6824fa81c7daf37fb9e77a',
    messagingSenderId: '804705700879',
    projectId: 'vinner-308ca',
    databaseURL: 'https://vinner-308ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vinner-308ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBASvKFRNZ2AtUrEL4JyGsWvV3sIffOa0w',
    appId: '1:804705700879:ios:05c782df8819ee24b9e77a',
    messagingSenderId: '804705700879',
    projectId: 'vinner-308ca',
    databaseURL: 'https://vinner-308ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vinner-308ca.appspot.com',
    iosBundleId: 'com.egoncastle.users',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASvKFRNZ2AtUrEL4JyGsWvV3sIffOa0w',
    appId: '1:804705700879:ios:05c782df8819ee24b9e77a',
    messagingSenderId: '804705700879',
    projectId: 'vinner-308ca',
    databaseURL: 'https://vinner-308ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vinner-308ca.appspot.com',
    iosBundleId: 'com.egoncastle.users',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOjW1IrUtqTpMWHm_GG4gSib8TGBTmHi4',
    appId: '1:804705700879:web:36fe1008dcc16be2b9e77a',
    messagingSenderId: '804705700879',
    projectId: 'vinner-308ca',
    authDomain: 'vinner-308ca.firebaseapp.com',
    databaseURL: 'https://vinner-308ca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vinner-308ca.appspot.com',
    measurementId: 'G-VWB1WFQMCY',
  );
}
